import { supabase } from './supabase.js';

export const $=id=>document.getElementById(id);
export const escapeHtml=(v='')=>String(v).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
export const formatDate=v=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
export const formatDateTime=v=>v?new Date(v).toLocaleString('pt-BR'):'—';

function publicView(){document.documentElement.dataset.guest='true';if(!document.getElementById('publicViewStyle')){const s=document.createElement('style');s.id='publicViewStyle';s.textContent='#newBtn,#editModal,#modal .form-actions,.status-edit,.edit,.delete{display:none!important}';document.head.appendChild(s)}if($('userEmail'))$('userEmail').textContent='Visualização pública';if($('profileEmail'))$('profileEmail').textContent='Visualização pública';const p=document.querySelector('.profile-text');if(p&&!p.querySelector('.public-login-link')){const a=document.createElement('a');a.className='public-login-link';a.href='./index.html';a.textContent='Entrar para editar';a.style.cssText='font-size:11px;text-decoration:underline;display:inline-block;margin-top:3px';p.appendChild(a)}}
export async function requireAuth(){const{data}=await supabase.auth.getUser();if(!data.user){publicView();return null}document.documentElement.dataset.guest='false';const e=data.user.email||'';if($('userEmail'))$('userEmail').textContent=e;if($('profileEmail'))$('profileEmail').textContent=e;return data.user}

const icons={dashboard:'▦',solicitacoes:'▤',clientes:'●',relatorios:'▥'};
function modern(){if(document.getElementById('modernUIStyle'))return;const s=document.createElement('style');s.id='modernUIStyle';s.textContent=`
:root{--navy:#073f69;--navy-deep:#052f50;--accent:#2d83bd}
body{background:linear-gradient(135deg,#f4f7fa,#eef3f7)}
.sidebar{width:230px;padding:24px 14px;background:linear-gradient(180deg,#073f69,#06385e 55%,#052f50);box-shadow:8px 0 28px rgba(3,34,56,.12)}
.brand{padding:4px 10px 22px;border-bottom:1px solid rgba(255,255,255,.18)}
.brand-logo{height:88px!important;min-height:88px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;overflow:visible!important;padding:0!important;margin:0!important;background-image:url('./assets/logo-security-original.svg?v=21')!important;background-repeat:no-repeat!important;background-position:left center!important;background-size:190px auto!important}
.brand-logo>img.security-logo{display:block!important;position:relative!important;z-index:5!important;width:190px!important;height:auto!important;max-width:190px!important;max-height:none!important;object-fit:contain!important;object-position:left center!important;filter:none!important;margin:0!important;visibility:visible!important;opacity:1!important}
.brand-logo>span,.brand-logo:before,.brand-logo:after{display:none!important;content:none!important}
.nav{padding-top:22px;gap:6px}.nav a{min-height:44px;padding:11px 13px;border-radius:10px;gap:12px;color:rgba(255,255,255,.92);font-size:13px}.nav a:hover{background:rgba(255,255,255,.09);transform:translateX(2px)}.nav a.active{background:rgba(85,154,199,.38);box-shadow:inset 3px 0 #fff;color:#fff}.nav .icon{width:20px;height:20px;flex-basis:20px;display:grid;place-items:center;color:#fff;font-size:16px;line-height:1}.nav .icon:before,.nav .icon:after{display:none!important;content:none!important}.nav a .icon{font-family:Arial,sans-serif;font-weight:700}
.sidebar-footer{font-size:10px;padding:12px 7px;color:#b9d4e6}.main{margin-left:230px;width:calc(100% - 230px)}.top-header{height:64px;padding:0 28px;background:#fff;border-bottom:1px solid #e4ebf0}.profile{padding:6px 9px 6px 13px;border:1px solid #e4ebf0;border-radius:12px;background:#fff}.avatar{width:31px;height:31px;background:#0a4674}.content{padding:28px}.cards{gap:14px}.metric,.panel{border-radius:13px;box-shadow:0 8px 24px rgba(23,56,79,.06)}
@media(max-width:1050px){.sidebar{width:210px}.main{margin-left:210px;width:calc(100% - 210px)}.brand-logo>img.security-logo{width:170px!important;max-width:170px!important}}
@media(max-width:700px){.sidebar{width:70px;padding:14px 8px}.brand{padding:0 5px 16px}.brand-logo{height:42px!important;min-height:42px!important;justify-content:center!important;background-size:54px auto!important;background-position:center center!important}.brand-logo>img.security-logo{width:54px!important;max-width:54px!important;height:auto!important}.main{margin-left:70px;width:calc(100% - 70px)}.nav a{justify-content:center;padding:11px 8px}.nav a span:not(.icon){display:none}}
`;document.head.appendChild(s)}

export function setupShell(active){modern();const b=document.querySelector('.brand-logo');if(b){b.innerHTML='<img class="security-logo" src="./assets/logo-security-original.svg?v=21" alt="Security — Segurança e Serviços">'}document.querySelectorAll('.nav a').forEach(a=>{a.classList.toggle('active',a.dataset.page===active);const i=a.querySelector('.icon');if(i)i.textContent=icons[a.dataset.page]||''});const btn=$('logoutButton');if(btn)btn.addEventListener('click',async()=>{await supabase.auth.signOut();location.href='./index.html'})}
export function badgeStatus(status){const m={aberto:['badge-open','Aberto'],'em andamento':['badge-progress','Em andamento'],concluido:['badge-done','Concluído'],concluída:['badge-done','Concluída'],concluído:['badge-done','Concluído']};const x=m[String(status||'').toLowerCase()]||['badge-open',status||'Aberto'];return `<span class="badge ${x[0]}">${escapeHtml(x[1])}</span>`}
export function badgePriority(priority){const p=String(priority||'Média').toLowerCase();const c=p.includes('crít')||p.includes('crit')?'badge-critical':p.includes('alta')?'badge-high':'badge-medium';return `<span class="badge ${c}">${escapeHtml(priority||'Média')}</span>`}
export async function getSolicitacoes(){const{data,error}=await supabase.from('solicitacoes').select('*').order('criado_em',{ascending:false});if(error)throw error;return data||[]}
export async function getClientes(){const{data,error}=await supabase.from('clientes').select('*').order('nome');if(error)throw error;return data||[]}
